name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@1.4.0
        with:
          github_access_token: ${{ secrets.ANGULAR_TOKEN }}
          build_configuration: build
          base_href: /Juju/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/juju

permissions:
  contents: write
